added WALES data and fixed categories
orcestra-campaign/book pull request #170
Opened 2024-08-18 17:44 UTC by bjorn-stevens

2024-08-18 17:57 UTC, lkluft requested changes

2024-08-18 17:57 UTC, lkluft commented on orcestra_book/reports/HALO-20240811a.md
> +
This card is missing the three closing backticks

2024-08-18 17:57 UTC, lkluft commented on orcestra_book/figures/HALO-20240811a/0811-wales-3d.png
Though the images are really cool we might want to reduce their size a bit 😉

2024-08-18 21:51 UTC, bjorn-stevens commented on orcestra_book/figures/HALO-20240811a/0811-wales-3d.png
okay, made the 3d image (the big one) smaller...

2024-08-21 09:45 UTC, d70-t commented
This PR seems to be good for a merge after a rebase (including a squash to remove the large files from the history).

2024-08-21 13:51 UTC, lkluft approved these changes

2024-08-21 13:57 UTC, merged