Added quicklook plots for 20240822 and 20240825
orcestra-campaign/book pull request #302
Opened 2024-08-29 15:43 UTC by KevinWolf-90

2024-08-29 18:55 UTC, lkluft requested changes
This PR seems a little off. It only adds one image (even though the title says two), the image is not linked in any report, and it includes a NetCDF file.

Please let me know if you need help getting this PR into a mergeable form.

2024-08-29 18:55 UTC, lkluft commented on orcestra_book/figures/HALO-20240822a/HALO_20240822a_SMART.nc
I assume that this NetCDF file was added accidentally?

2024-08-29 22:24 UTC, bjorn-stevens approved these changes

2024-08-30 10:36 UTC, lkluft approved these changes

2024-08-30 10:39 UTC, merged