Add sub-campaign Clarinet
orcestra-campaign/book pull request #39
Opened 2024-07-02 11:47 UTC by yu71ng

2024-07-02 12:47 UTC, lkluft commented
Hey Yuting, it looks like you got tangled up with your local branches. My current guess is that you created a the new branch `clarinet` from an existing branch with a new data policy instead of the `main` branch.

There are several ways to fix this. I would suggest that you perform an [interactive rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) from `clarinet` onto `main` and drop the `Add data policy` commit.

Let me know if you need any help :)

2024-07-02 13:36 UTC, yu71ng commented
Alright... I tried to perform the interactive rebase... but I probably shouldn't force-pushed it, right? 😅

2024-07-02 16:06 UTC, lkluft commented
Actually, you **must** force-push after a rebase, because you have changed the history of the branch. Everything is now clean and ready to merge. Thanks for the contribution and the cleanup! :)

2024-07-02 16:07 UTC, lkluft requested changes

2024-07-02 16:07 UTC, lkluft commented on orcestra_book/clarinet.md
> +## CLARINET
I think the heading in a document need to start on level H1 (e.g. `# CLARINET`)

2024-07-02 16:10 UTC, lkluft requested changes

2024-07-02 16:10 UTC, lkluft commented on orcestra_book/clarinet.md
> +### CLoud and Aerosol Remote sensing for EarThcare
Headings in a document need to start on level H1, i.e.:
```suggestion
# CLARINET
## CLoud and Aerosol Remote sensing for EarThcare
```

2024-07-02 16:37 UTC, yu71ng commented
I see... well... learning by doing 😅

2024-07-03 08:16 UTC, lkluft approved these changes
Thanks for your contribution! :)

2024-07-03 08:16 UTC, merged