Added BACARDI QLs for 0829, 0831, 0924 and 0926
orcestra-campaign/book pull request #533
Opened 2024-10-02 11:33 UTC by annaluebke

2024-10-02 14:29 UTC, lkluft requested changes

2024-10-02 14:29 UTC, lkluft commented on orcestra_book/figures/HALO-20240924a/HALO_20240924a_BACARDI_QL.png
Could you please add/uncomment this plot to the report of HALO-20240924a?

2024-10-04 10:15 UTC, bjorn-stevens approved these changes
unless I read it wrong it seems like the requested changes have been addressed

2024-10-08 08:46 UTC, annaluebke commented on orcestra_book/figures/HALO-20240924a/HALO_20240924a_BACARDI_QL.png
Oops, I completely missed that. The plot is now uncommented.

2024-10-08 15:14 UTC, lkluft approved these changes

2024-10-08 15:14 UTC, merged